name: Post an Article

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs:
      date:
        description: "Article date formatted as YYYY-MM-DD"
        required: false

jobs:
  post-at-article:
    name: Post an Article to Telegram Channels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Post an Article
        env:
          TELEGRAPH_TOKEN: ${{ secrets.TELEGRAPH_TOKEN }}
          TELEGRAPH_AUTHOR: ${{ secrets.TELEGRAPH_AUTHOR }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          BOT_ADMIN: ${{ secrets.BOT_ADMIN }}
          CHANNEL_IDS: ${{ secrets.CHANNEL_IDS }}
          ARTICLE_DATE: ${{ inputs.date }}
        run: go run ./cmd/post-to-channel
